name: Test with Maven

# Do lots of tests :)
on:
  workflow_dispatch:
  pull_request:
    branches: [ main, master ]
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
      - '!main'     # excludes main

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          # this distribution is cached by github actions
          distribution: 'temurin'
          # jdk version to use, specified in pom.xml
          java-version: '21'
          # use the github actions cached jdk if available.
          check-latest: false
      - name: mvn compile
        # maven almost always fails to generate sources correctly without cleaning
        # transfer progress is disabled to avoid spamming the log with progress bars
        run: mvn clean compile --file pom.xml --no-transfer-progress
      - name: mvn javafx:jlink
        run: mvn javafx:jlink --file pom.xml --no-transfer-progress
      - name: upload build
        uses: actions/upload-artifact@v4
        with:
          path: target/walmartktane.zip
